version: '2'
services:
  4boxteste-app:
    image: 4boxteste
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://4boxteste-mysql:3306/4boxteste?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://4boxteste-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://4boxteste-elasticsearch:9200
    ports:
      - 80:80
  4boxteste-mysql:
    extends:
      file: mysql.yml
      service: 4boxteste-mysql
  4boxteste-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: 4boxteste-elasticsearch
